"""added column

Revision ID: 42b74a9fd0a9
Revises: a098daca54d5
Create Date: 2023-03-20 20:37:13.812673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b74a9fd0a9'
down_revision = 'a098daca54d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_message_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_message_email'), type_='unique')

    # ### end Alembic commands ###
